// GeoTwin Mantine UI Components
// Centralized exports for all Mantine-based components

export { Button } from './Button';
export { Card } from './Card';

// Re-export commonly used Mantine components with consistent naming
export {
  Text,
  Title,
  Group,
  Stack,
  Space,
  Divider,
  Container,
  Grid,
  SimpleGrid,
  Flex,
  Box,
  Center,
  Loader,
  Progress,
  Badge,
  Tooltip,
  Popover,
  Modal,
  Drawer,
  Navbar,
  Accordion,
  Tabs,
  TextInput,
  NumberInput,
  Select,
  MultiSelect,
  Checkbox,
  Radio,
  Switch,
  Slider,
  RangeSlider,
  Textarea,
  PasswordInput,
  DatePicker,
  TimeInput,
  ColorInput,
  FileInput,
  JsonInput,
  Autocomplete,
  Chip,
  SegmentedControl,
  Rating,
  Table,
  ScrollArea,
  Anchor,
  Breadcrumbs,
  Pagination,
  Stepper,
  Timeline,
  Spotlight,
  ActionIcon,
  CloseButton,
  CopyButton,
  FileButton,
  UnstyledButton,
  Alert,
  Notification,
  LoadingOverlay,
  Skeleton,
  Transition,
  Collapse,
  Affix,
  BackgroundImage,
  Image,
  Overlay,
  Paper,
  ThemeIcon,
  Avatar,
  Indicator,
  Kbd,
  Mark,
  Highlight,
  Code,
  Blockquote,
  List,
  ColorSwatch,
  ColorPicker,
  HueSlider,
  AlphaSlider,
  Spoiler,
  Menu,
  HoverCard,
  FocusTrap,
  Portal,
  Transition as MantineTransition,
  useMantineTheme,
  useMantineColorScheme,
} from '@mantine/core';

// Re-export hooks
export {
  useLocalStorage,
  useSessionStorage,
  useHover,
  useClickOutside,
  useDisclosure,
  useToggle,
  useCounter,
  useListState,
  useInputState,
  useViewportSize,
  useWindowScroll,
  useElementSize,
  useResizeObserver,
  useIntersection,
  useScrollIntoView,
  useHeadroom,
  useHotkeys,
  useIdle,
  useInterval,
  useTimeout,
  useDebouncedValue,
  useThrottledValue,
  useMediaQuery,
  useColorScheme,
  useOs,
  useNetwork,
  useClipboard,
  useFullscreen,
  useDocumentTitle,
  useFavicon,
  usePageLeave,
  useHash,
  useValidatedState,
  useForceUpdate,
  useDidUpdate,
  useIsomorphicEffect,
  useMergedRef,
  useUncontrolled,
  useId,
  usePrevious,
  useQueue,
  useSet,
  useMap,
  useShallowEffect,
  useEyeDropper,
  useMove,
  useMouse,
  useTextSelection,
} from '@mantine/hooks';

// Re-export form utilities
export {
  useForm as useMantineForm,
  isEmail,
  isNotEmpty,
  hasLength,
  matches,
  isInRange,
} from '@mantine/form';

// Re-export notifications
export {
  showNotification,
  hideNotification,
  cleanNotifications,
  updateNotification,
  notifications,
} from '@mantine/notifications';
